#############################################################################
# Makefile for building: nvr-verup
# Generated by qmake (2.01a) (Qt 4.7.0) on: ? 1? 2 16:04:19 2018
# Project:  ../nvr-verup/nvr-verup.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.7.0/bin/qmake -spec /usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/linux-g++ CONFIG+=debug -o Makefile ../nvr-verup/nvr-verup.pro
#############################################################################
ifndef TOPDIR
TOPDIR =/home/mcc/git/G2NVR_APL_caoty/G3NVR_APL_EUC
CROSS        = arm-hisiv400-linux-
endif
####### Compiler, tools and options
LIBQTBASE     = $(TOPDIR)/lib/qt/4.7.0_G3NVR
CC            = $(CROSS)gcc
CXX           = $(CROSS)g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
DEFINES		+= -DHYRON_BUILD
CFLAGS_MUST		= -march=armv7-a -mfloat-abi=softfp -mfpu=neon-vfpv4 -mno-unaligned-access -fno-aggressive-loop-optimizations
CFLAGS        = -pipe -O2 -Wall -W -rdynamic $(CFLAGS_MUST) -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -rdynamic $(CFLAGS_MUST) -D_REENTRANT $(DEFINES)
INCPATH       = -I$(LIBQTBASE)/mkspecs/qws/linux-arm-g++ -I. -I$(LIBQTBASE)/include/QtCore -I$(LIBQTBASE)/include/QtNetwork \
                -I$(LIBQTBASE)/include/QtGui -I$(LIBQTBASE)/include/QtWebKit -I$(LIBQTBASE)/include \
                -I. -I../nvr-verup -I.
LINK          = $(CROSS)g++
#LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.7.0/lib
#LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.7.0/lib -lQtGui -L/usr/local/Trolltech/QtEmbedded-4.7.0/lib -lQtNetwork -lQtCore -lpthread 
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L$(LIBQTBASE)/lib -lrt
LIBS		+= -lQtWebKit -lQtGui -lQtScript -lQtNetwork -lQtCore -lpthread
AR            = $(CROSS)ar cqs
RANLIB        = 
#QMAKE         = /usr/local/Trolltech/QtEmbedded-4.7.0/bin/qmake
QMAKESPEC     = $(LIBQTBASE)/mkspecs/qws/linux-arm-g++
QMAKE         = $(LIBQTBASE)/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../nvr-verup/versionUp.cpp \
		../nvr-verup/main.cpp \
		../nvr-verup/moc_versionUp.cpp \
		../nvr-verup/qrc_verup.cpp
OBJECTS       = versionUp.o \
		main.o \
		moc_versionUp.o \
		qrc_verup.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/include_source_dir.prf \
		../nvr-verup/nvr-verup.pro
QMAKE_TARGET  = nvr-verup
DESTDIR       = 
TARGET        = nvr-verup
#QMFILES       = res/translate/verup_jp.qm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../nvr-verup/nvr-verup.pro  $(LIBQTBASE)/mkspecs/qws/linux-arm-g++/qmake.conf \
		$(LIBQTBASE)/mkspecs/common/g++.conf \
		$(LIBQTBASE)/mkspecs/common/unix.conf \
		$(LIBQTBASE)/mkspecs/common/linux.conf \
		$(LIBQTBASE)/mkspecs/common/qws.conf \
		$(LIBQTBASE)/mkspecs/qconfig.pri \
		$(LIBQTBASE)/mkspecs/modules/qt_webkit_version.pri \
		$(LIBQTBASE)/mkspecs/features/qt_functions.prf \
		$(LIBQTBASE)/mkspecs/features/qt_config.prf \
		$(LIBQTBASE)/mkspecs/features/exclusive_builds.prf \
		$(LIBQTBASE)/mkspecs/features/default_pre.prf \
		$(LIBQTBASE)/mkspecs/features/release.prf \
		$(LIBQTBASE)/mkspecs/features/default_post.prf \
		$(LIBQTBASE)/mkspecs/features/warn_on.prf \
		$(LIBQTBASE)/mkspecs/features/qt.prf \
		$(LIBQTBASE)/mkspecs/features/unix/thread.prf \
		$(LIBQTBASE)/mkspecs/features/moc.prf \
		$(LIBQTBASE)/mkspecs/features/resources.prf \
		$(LIBQTBASE)/mkspecs/features/uic.prf \
		$(LIBQTBASE)/mkspecs/features/yacc.prf \
		$(LIBQTBASE)/mkspecs/features/lex.prf \
		$(LIBQTBASE)/mkspecs/features/include_source_dir.prf \
		$(LIBQTBASE)/lib/libQtWebKit.prl \
		$(LIBQTBASE)/lib/libQtScript.prl \
		$(LIBQTBASE)/lib/libQtCore.prl \
		$(LIBQTBASE)/lib/libQtGui.prl \
		$(LIBQTBASE)/lib/libQtNetwork.prl

#Makefile: ../nvr-verup/nvr-verup.pro  /usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/g++.conf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/unix.conf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/linux.conf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/qconfig.pri \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/modules/qt_webkit_version.pri \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt_functions.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt_config.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/exclusive_builds.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/default_pre.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/debug.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/default_post.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/warn_on.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/unix/thread.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/moc.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/resources.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/uic.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/yacc.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/lex.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/include_source_dir.prf \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/lib/libQtGui.prl \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/lib/libQtNetwork.prl \
#		/usr/local/Trolltech/QtEmbedded-4.7.0/lib/libQtCore.prl
#	$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/linux-g++ CONFIG+=debug -o Makefile ../nvr-verup/nvr-verup.pro

$(LIBQTBASE)/mkspecs/common/g++.conf:
$(LIBQTBASE)/mkspecs/common/unix.conf:
$(LIBQTBASE)/mkspecs/common/linux.conf:
$(LIBQTBASE)/mkspecs/common/qws.conf:
$(LIBQTBASE)/mkspecs/qconfig.pri:
$(LIBQTBASE)/mkspecs/modules/qt_webkit_version.pri:
$(LIBQTBASE)/mkspecs/features/qt_functions.prf:
$(LIBQTBASE)/mkspecs/features/qt_config.prf:
$(LIBQTBASE)/mkspecs/features/exclusive_builds.prf:
$(LIBQTBASE)/mkspecs/features/default_pre.prf:
$(LIBQTBASE)/mkspecs/features/release.prf:
$(LIBQTBASE)/mkspecs/features/default_post.prf:
$(LIBQTBASE)/mkspecs/features/warn_on.prf:
$(LIBQTBASE)/mkspecs/features/qt.prf:
$(LIBQTBASE)/mkspecs/features/unix/thread.prf:
$(LIBQTBASE)/mkspecs/features/moc.prf:
$(LIBQTBASE)/mkspecs/features/resources.prf:
$(LIBQTBASE)/mkspecs/features/uic.prf:
$(LIBQTBASE)/mkspecs/features/yacc.prf:
$(LIBQTBASE)/mkspecs/features/lex.prf:
$(LIBQTBASE)/mkspecs/features/include_source_dir.prf:
$(LIBQTBASE)/lib/libQtWebKit.prl:
$(LIBQTBASE)/lib/libQtScript.prl:
$(LIBQTBASE)/lib/libQtCore.prl:
$(LIBQTBASE)/lib/libQtGui.prl:
$(LIBQTBASE)/lib/libQtNetwork.prl:

#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/g++.conf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/unix.conf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/common/linux.conf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/qconfig.pri:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/modules/qt_webkit_version.pri:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt_functions.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt_config.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/exclusive_builds.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/default_pre.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/debug.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/default_post.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/warn_on.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/qt.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/unix/thread.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/moc.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/resources.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/uic.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/yacc.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/lex.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/features/include_source_dir.prf:
#/usr/local/Trolltech/QtEmbedded-4.7.0/lib/libQtGui.prl:
#/usr/local/Trolltech/QtEmbedded-4.7.0/lib/libQtNetwork.prl:
#/usr/local/Trolltech/QtEmbedded-4.7.0/lib/libQtCore.prl:
#qmake:  FORCE
#	@$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.7.0/mkspecs/linux-g++ CONFIG+=debug -o Makefile ../nvr-verup/nvr-verup.pro

#dist: 
#	@$(CHK_DIR_EXISTS) ../nvr-verup/.tmp/nvr-verup1.0.0 || $(MKDIR) ../nvr-verup/.tmp/nvr-verup1.0.0 
#	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../nvr-verup/.tmp/nvr-verup1.0.0/ && $(COPY_FILE) --parents ../nvr-verup/versionUp.h ../nvr-verup/.tmp/nvr-verup1.0.0/ && $(COPY_FILE) --parents ../nvr-verup/versionUp.cpp ../nvr-verup/main.cpp ../nvr-verup/.tmp/nvr-verup1.0.0/ && (cd `dirname ../nvr-verup/.tmp/nvr-verup1.0.0` && $(TAR) nvr-verup1.0.0.tar nvr-verup1.0.0 && $(COMPRESS) nvr-verup1.0.0.tar) && $(MOVE) `dirname ../nvr-verup/.tmp/nvr-verup1.0.0`/nvr-verup1.0.0.tar.gz . && $(DEL_FILE) -r ../nvr-verup/.tmp/nvr-verup1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core $(TARGET)

#clean:compiler_clean 
#	-$(DEL_FILE) $(OBJECTS)
#	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_versionUp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_versionUp.cpp
moc_versionUp.cpp: ../nvr-verup/versionUp.h
	$(LIBQTBASE)/bin/moc $(DEFINES) $(INCPATH) ../nvr-verup/versionUp.h -o moc_versionUp.cpp
#moc_versionUp.cpp: ../nvr-verup/versionUp.h
#	/usr/local/Trolltech/QtEmbedded-4.7.0/bin/moc $(DEFINES) $(INCPATH) ../nvr-verup/versionUp.h -o moc_versionUp.cpp

compiler_rcc_make_all: qrc_verup.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_verup.cpp
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean

qrc_verup.cpp: verup.qrc \
		res/translate/verup_jp.qm
	$(LIBQTBASE)/bin/rcc -name verup verup.qrc -o qrc_verup.cpp
res/translate/verup_jp.qm:  res/translate/verup_jp.ts
	$(LIBQTBASE)/bin/lrelease res/translate/verup_jp.ts 

####### Compile

versionUp.o: ../nvr-verup/versionUp.cpp ../nvr-verup/versionUp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o versionUp.o ../nvr-verup/versionUp.cpp

main.o: ../nvr-verup/main.cpp ../nvr-verup/versionUp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../nvr-verup/main.cpp

moc_versionUp.o: moc_versionUp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_versionUp.o moc_versionUp.cpp

qrc_verup.o: qrc_verup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_verup.o qrc_verup.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/ 
	-$(INSTALL_FILE) /home/mcc/qt/qt-embedded/qt-embedded-example/qws/nvr-verup/versionUp.cpp $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/
	-$(INSTALL_FILE) /home/mcc/qt/qt-embedded/qt-embedded-example/qws/nvr-verup/main.cpp $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/
	-$(INSTALL_FILE) /home/mcc/qt/qt-embedded/qt-embedded-example/qws/nvr-verup/versionUp.h $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/
	-$(INSTALL_FILE) /home/mcc/qt/qt-embedded/qt-embedded-example/qws/nvr-verup/nvr-verup.pro $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/versionUp.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/versionUp.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/nvr-verup.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/Trolltech/QtEmbedded-4.7.0/examples/qws/nvr-verup/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

